"""добавлена таблица для сообщений в групповых чатах

Revision ID: 06d36f8d1ae2
Revises: a47ae0a8a56e
Create Date: 2025-08-22 12:41:44.796865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "06d36f8d1ae2"
down_revision: Union[str, Sequence[str], None] = "a47ae0a8a56e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "GroupMessages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sender", sa.UUID(), nullable=True),
        sa.Column("send_time", sa.DateTime(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recipients", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.ForeignKeyConstraint(
            ["sender"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_GroupMessages_id"), "GroupMessages", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_GroupMessages_id"), table_name="GroupMessages")
    op.drop_table("GroupMessages")
    # ### end Alembic commands ###
