"""initial migration

Revision ID: 15fe492c8cac
Revises:
Create Date: 2025-07-27 12:13:59.358912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "15fe492c8cac"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Chats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("users", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Chats_id"), "Chats", ["id"], unique=False)
    op.create_table(
        "Users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Users_email"), "Users", ["email"], unique=True)
    op.create_index(op.f("ix_Users_id"), "Users", ["id"], unique=False)
    op.create_index(op.f("ix_Users_username"), "Users", ["username"], unique=True)
    op.create_table(
        "Messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sender", sa.Uuid(), nullable=True),
        sa.Column("send_time", sa.DateTime(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["Chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Messages_chat_id"), "Messages", ["chat_id"], unique=False)
    op.create_index(op.f("ix_Messages_id"), "Messages", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Messages_id"), table_name="Messages")
    op.drop_index(op.f("ix_Messages_chat_id"), table_name="Messages")
    op.drop_table("Messages")
    op.drop_index(op.f("ix_Users_username"), table_name="Users")
    op.drop_index(op.f("ix_Users_id"), table_name="Users")
    op.drop_index(op.f("ix_Users_email"), table_name="Users")
    op.drop_table("Users")
    op.drop_index(op.f("ix_Chats_id"), table_name="Chats")
    op.drop_table("Chats")
    # ### end Alembic commands ###
