"""изменен Messages

Revision ID: 3974b730861e
Revises: 751cb415ce1b
Create Date: 2025-08-01 12:41:03.478783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3974b730861e'
down_revision: Union[str, Sequence[str], None] = '751cb415ce1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Messages', sa.Column('user2', sa.Uuid(), nullable=False))
    op.drop_column('Messages', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Messages', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Messages', 'user2')
    # ### end Alembic commands ###
