"""Add img field to Users

Revision ID: 3d98ffec9309
Revises: 94a285337383
Create Date: 2025-07-27 21:22:21.974715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d98ffec9309"
down_revision: Union[str, Sequence[str], None] = "94a285337383"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Users", sa.Column("img", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Users", "img")
    # ### end Alembic commands ###
