"""изменена таблица groupChatMessages

Revision ID: 4c5081439d81
Revises: 06d36f8d1ae2
Create Date: 2025-08-22 15:09:29.922483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "4c5081439d81"
down_revision: Union[str, Sequence[str], None] = "06d36f8d1ae2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("GroupMessages", sa.Column("group_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "GroupMessages", "GroupChat", ["group_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "GroupMessages", type_="foreignkey")
    op.drop_column("GroupMessages", "group_id")
    # ### end Alembic commands ###
