"""Add users as UUID array in Chat

Revision ID: 751cb415ce1b
Revises: b4f5c4db75bd
Create Date: 2025-07-28 12:33:59.907794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751cb415ce1b'
down_revision: Union[str, Sequence[str], None] = 'b4f5c4db75bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
