"""замена Chat_id на username в messages

Revision ID: ae4916464719
Revises: 3d98ffec9309
Create Date: 2025-07-28 09:33:55.071722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ae4916464719"
down_revision: Union[str, Sequence[str], None] = "3d98ffec9309"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Messages",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_index(op.f("ix_Messages_chat_id"), table_name="Messages")
    op.drop_constraint(op.f("Messages_chat_id_fkey"), "Messages", type_="foreignkey")
    op.drop_column("Messages", "chat_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Messages", sa.Column("chat_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("Messages_chat_id_fkey"), "Messages", "Chats", ["chat_id"], ["id"]
    )
    op.create_index(op.f("ix_Messages_chat_id"), "Messages", ["chat_id"], unique=False)
    op.drop_column("Messages", "username")
    # ### end Alembic commands ###
