"""теперь в user другой primary key

Revision ID: b4f5c4db75bd
Revises: ed93b3b028ff
Create Date: 2025-07-28 12:20:50.454421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4f5c4db75bd'
down_revision: Union[str, Sequence[str], None] = 'ed93b3b028ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Chats', 'users',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.UUID()),
               existing_nullable=True)
    op.alter_column('Users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Chats', 'users',
               existing_type=sa.ARRAY(sa.UUID()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###
