"""изменено поле sender в message

Revision ID: ed93b3b028ff
Revises: ae4916464719
Create Date: 2025-07-28 11:33:32.151711

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed93b3b028ff"
down_revision: Union[str, Sequence[str], None] = "ae4916464719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.drop_constraint("Messages_sender_fkey", "Messages", type_="foreignkey")
    op.execute('ALTER TABLE "Chats" ALTER COLUMN users TYPE uuid[] USING users::uuid[]')
    op.execute(
        'ALTER TABLE "Messages" ALTER COLUMN sender TYPE uuid USING sender::uuid'
    )
    op.create_foreign_key(
        "Messages_sender_fkey",
        "Messages",
        "Users",
        ["sender"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Messages", type_="foreignkey")
    op.execute('ALTER TABLE "Chats" ALTER COLUMN users TYPE text[] USING users::text[]')
    op.create_foreign_key(
        op.f("Messages_sender_fkey"), "Messages", "Users", ["sender"], ["id"]
    )
    op.alter_column(
        "Messages",
        "sender",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
